export interface BackgroundIcon {
  icon: string;
  top: string;
  left: string;
  rotate: string;
  xx: number;
  xy: number;
  color: string;
}

export const BACKGROUND_ICONS: BackgroundIcon[] = [
  {
    icon: 'mdi:account-school-outline',
    top: '12%',
    left: '18%',
    rotate: '-15deg',
    xx: 1.35,
    xy: -0.2,
    color: '#EF4444',
  },
  {
    icon: 'mdi:music-note-eighth',
    top: '10%',
    left: '50%',
    rotate: '18deg',
    xx: -0.55,
    xy: 1.45,
    color: '#EAB308',
  },
  {
    icon: 'mdi:glasses',
    top: '14%',
    left: '82%',
    rotate: '10deg',
    xx: 0.2,
    xy: -1.6,
    color: '#84CC16',
  },
  {
    icon: 'mdi:skull-outline',
    top: '30%',
    left: '10%',
    rotate: '-20deg',
    xx: -1.4,
    xy: 0.1,
    color: '#06B6D4',
  },
  {
    icon: 'mdi:controller-classic-outline',
    top: '28%',
    left: '64%',
    rotate: '-25deg',
    xx: 0.85,
    xy: -1.35,
    color: '#0EA5E9',
  },
  {
    icon: 'mdi:shoe-formal',
    top: '34%',
    left: '40%',
    rotate: '-22deg',
    xx: 1.6,
    xy: 0.5,
    color: '#A3E635',
  },
  {
    icon: 'mdi:alarm',
    top: '50%',
    left: '15%',
    rotate: '30deg',
    xx: -1.1,
    xy: 1.0,
    color: '#10B981',
  },
  {
    icon: 'mdi:fish',
    top: '52%',
    left: '72%',
    rotate: '12deg',
    xx: 0.3,
    xy: 1.6,
    color: '#A855F7',
  },
  {
    icon: 'mdi:image-filter-drama-outline',
    top: '56%',
    left: '46%',
    rotate: '15deg',
    xx: -0.9,
    xy: -1.2,
    color: '#3B82F6',
  },
  {
    icon: 'mdi:umbrella-outline',
    top: '68%',
    left: '18%',
    rotate: '-12deg',
    xx: 1.25,
    xy: 0.95,
    color: '#D946EF',
  },
  {
    icon: 'mdi:dog',
    top: '66%',
    left: '86%',
    rotate: '14deg',
    xx: -1.55,
    xy: -0.65,
    color: '#8B5CF6',
  },
  {
    icon: 'mdi:lightbulb-on-outline',
    top: '72%',
    left: '38%',
    rotate: '-10deg',
    xx: 0.65,
    xy: -1.45,
    color: '#FB923C',
  },
  {
    icon: 'mdi:sword-cross',
    top: '86%',
    left: '22%',
    rotate: '6deg',
    xx: -1.3,
    xy: 0.55,
    color: '#22C55E',
  },
  {
    icon: 'mdi:heart-outline',
    top: '88%',
    left: '50%',
    rotate: '8deg',
    xx: 0.45,
    xy: -1.55,
    color: '#F87171',
  },
  {
    icon: 'mdi:star-outline',
    top: '90%',
    left: '78%',
    rotate: '-18deg',
    xx: 1.1,
    xy: 0.35,
    color: '#22D3EE',
  },
];
